[default]
timeout = 120

[vaureal_avenir]
title = "Vauréal - à venir"
url = "https://www.vaureal.fr/agenda/a-venir"
entrySelector = "div.views-row"
titleSelector = "div.wrapper"
linkSelector = "div.views-field-title>a"
contentSelector = "div.resume>p"
